// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCCjxidhvURHniYK_Qzg7eQ6zEpLSuxH8',
    appId: '1:65962508219:android:6fda4b64a5fc12ab4e4e9e',
    messagingSenderId: '65962508219',
    projectId: 'desafio-capyba-7ee84',
    databaseURL: 'https://desafio-capyba-7ee84-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-capyba-7ee84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARuK6fyh6s9eYpuSkn2pyu-K9iMtPxdHQ',
    appId: '1:65962508219:ios:02997d5afa4a257b4e4e9e',
    messagingSenderId: '65962508219',
    projectId: 'desafio-capyba-7ee84',
    databaseURL: 'https://desafio-capyba-7ee84-default-rtdb.firebaseio.com',
    storageBucket: 'desafio-capyba-7ee84.appspot.com',
    iosClientId: '65962508219-8kot8d2j9qa0a5f4giuto7rm35msi0o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviex',
  );
}
